# Site settings
title: Geospatial Response
subtitle: "Kitty Hurley"
email: katherine.d.hurley@gmail.com
description: "Kitty is a GIS developer and cartographer from Saint Paul, Minnesota. When she's not making and breaking web apps she can be spotted skating around local skating rinks."
baseurl: ""
url: "http://geospatialem.github.io/"
twitter_username: "geospatialem"
github_username:  "geospatialem"

# Build settings
markdown: kramdown
permalink: pretty

# Pagination
paginate: 5

# Sass
sass:
    style: :compressed